# Generated by Django 5.2.8 on 2025-11-26 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankCodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="은행 코드"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="은행 이름")),
            ],
            options={
                "verbose_name": "은행코드",
                "verbose_name_plural": "은행 코드 목록",
                "db_table": "bank_codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="계좌번호"
                    ),
                ),
                (
                    "account_purpose",
                    models.CharField(
                        max_length=50, verbose_name="계좌 용도(생활비/저축/투자 등)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="계좌 소유자",
                    ),
                ),
                (
                    "bank_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="accounts.bankcodes",
                        verbose_name="은행 코드",
                    ),
                ),
            ],
            options={
                "verbose_name": "계좌",
                "verbose_name_plural": "계좌목록",
                "db_table": "accounts",
                "ordering": ["-created_at"],
            },
        ),
    ]
