# Generated by Django 5.2.8 on 2025-12-02 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("expense", "총 지출"),
                            ("income", "총 수입"),
                            ("all", "전체"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="분석 대상",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        choices=[("weekly", "주간"), ("monthly", "월간")],
                        db_index=True,
                        max_length=10,
                        null=True,
                        verbose_name="분석 단위",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="분석 시작일")),
                ("period_end", models.DateField(verbose_name="분석 종료일")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="분석 요약"),
                ),
                (
                    "result_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="analysis/",
                        verbose_name="분석 그래프",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "가계부 분석",
                "verbose_name_plural": "가계부 분석 목록",
                "db_table": "analysis",
                "ordering": ["-created_at"],
            },
        ),
    ]
