# Generated by Django 5.2.8 on 2025-11-27 09:32

import apps.analysis.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('expense', '총 지출'), ('income', '총 수입')], db_index=True, max_length=10, verbose_name='분석 대상')),
                ('period', models.CharField(choices=[('weekly', '주간'), ('monthly', '월간')], db_index=True, max_length=10, verbose_name='분석 단위')),
                ('period_start', models.DateField(verbose_name='분석 시작일')),
                ('period_end', models.DateField(verbose_name='분석 종료일')),
                ('description', models.TextField(blank=True, help_text='분석 메모나 요약을 입력하세요.', null=True, verbose_name='분석 요약')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to=apps.analysis.utils.analysis_image_path, verbose_name='분석 그래프')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='users.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '가계부 분석',
                'verbose_name_plural': '가계부 분석 목록',
                'db_table': 'analysis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'target', 'period'], name='idx_user_target_period'), models.Index(fields=['period_start', 'period_end'], name='idx_period_range'), models.Index(fields=['-created_at'], name='idx_created_desc')],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='check_period_validity')],
            },
        ),
    ]
