# Generated by Django 5.2.8 on 2025-12-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="analysis",
            name="check_period_validity",
        ),
        migrations.RemoveIndex(
            model_name="analysis",
            name="idx_user_target_period",
        ),
        migrations.RemoveIndex(
            model_name="analysis",
            name="idx_period_range",
        ),
        migrations.RemoveIndex(
            model_name="analysis",
            name="idx_created_desc",
        ),
        migrations.AlterField(
            model_name="analysis",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="분석 요약"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="period",
            field=models.CharField(
                blank=True,
                choices=[("weekly", "주간"), ("monthly", "월간")],
                db_index=True,
                max_length=10,
                null=True,
                verbose_name="분석 단위",
            ),
        ),
    ]
