# Generated by Django 5.2.8 on 2025-12-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_remove_analysis_check_period_validity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="target",
            field=models.CharField(
                choices=[
                    ("expense", "총 지출"),
                    ("income", "총 수입"),
                    ("all", "전체"),
                ],
                db_index=True,
                max_length=10,
                verbose_name="분석 대상",
            ),
        ),
    ]
