# Generated by Django 5.2.8 on 2025-11-26 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deposit", models.BooleanField(default=False)),
                ("amount", models.IntegerField(default=0)),
                ("category", models.CharField(blank=True, max_length=8, null=True)),
                ("content", models.CharField(blank=True, max_length=64, null=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_id",
                    models.ForeignKey(
                        db_column="account_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.accounts",
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
            },
        ),
    ]
