# Generated by Django 5.2.8 on 2025-12-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="balance_after",
            field=models.IntegerField(default=0),
        ),
    ]
