# Generated by Django 5.2.8 on 2025-12-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction_balance_after"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="balance_after",
            field=models.BigIntegerField(default=0),
        ),
    ]
