# Generated by Django 5.2.8 on 2025-11-25 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="이메일"
                    ),
                ),
                ("username", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=16)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "사용자"),
                            ("admin", "관리자"),
                            ("superuser", "슈퍼유저"),
                        ],
                        default="user",
                        max_length=20,
                        verbose_name="권한",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자",
            },
        ),
        migrations.CreateModel(
            name="BlacklistToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklist_tokens",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "블랙리스트 토큰",
                "verbose_name_plural": "블랙리스트 토큰",
            },
        ),
    ]
