# Generated by Django 5.2.8 on 2025-11-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklisttoken",
            name="token",
            field=models.CharField(max_length=500),
        ),
    ]
